### ISSUE TITLE
"dist must be a Distribution instance"

### ISSUE THREAD

**Issue by chyphen7** [skyhehe123/VoxelNet-pytorch#8]
Trying to ru python3 nms/build.py and getting errors:

Traceback (most recent call last):
  File "G:\VoxelNet-pytorch\nms\build.py", line 23, in <module>
    ffi = BuildExtension(
  File "D:\anaconda3\envs\py3\lib\site-packages\torch\utils\cpp_extension.py", line 361, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "D:\anaconda3\envs\py3\lib\site-packages\setuptools\__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "D:\anaconda3\envs\py3\lib\distutils\cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

I am getting the same errors on Windows 10 and uBuntu 18.04.   I have tried out several suggestions, but in vain.  Any good suggestions about how to fix the error?  

Thanks,
CC

**Comment by hjfenghj** [comment]
hello，have you sloved the problem?would you please give me some suggest

**Comment by FengJ130** [comment]
Hello, my friend. i also have this problem today, is here somebody sovled this problem?
thanks

**Comment by hjfenghj** [comment]
hello，I can not solve this problem,I don.t use the  function named "draw boxes";And this project can't save the model and the test branch;So I think if you can other choice,I advise you can use other project


| |
冯浩俊
|
|
***@***.***
|
On 7/13/2022 ***@***.***> wrote：

Hello, my friend. i also have this problem today, is here somebody sovled this problem?
thanks
